# Generated by Django 2.2.6 on 2019-11-19 03:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Extension',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('number', models.CharField(default='0', max_length=12, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=12)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='Add_New_ATM_Card',
            fields=[
                ('card_number', models.CharField(default='0', max_length=16, primary_key=True, serialize=False)),
                ('pin', models.CharField(max_length=4)),
                ('account_name', models.CharField(max_length=200)),
                ('date_issued', models.DateField(null=True)),
                ('expiry_date', models.DateField(null=True)),
                ('address', models.CharField(default='', max_length=200)),
                ('balance', models.CharField(default='0', max_length=20)),
                ('phone_number', models.CharField(default='', max_length=10)),
                ('card_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=10)),
                ('two_factor_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=10)),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Atm.Account_Extension')),
            ],
            options={
                'verbose_name': 'New ATM card',
                'verbose_name_plural': 'New ATM card',
            },
        ),
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('address', models.CharField(default='0', max_length=200, primary_key=True, serialize=False, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default='0', max_digits=20)),
            ],
            options={
                'verbose_name': 'ATM',
                'verbose_name_plural': 'ATMs',
            },
        ),
        migrations.CreateModel(
            name='View_ATM_Status',
            fields=[
                ('ATM_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Atm.ATM')),
                ('ATM_status', models.CharField(choices=[('Active', 'Active'), ('Down', 'Down')], default='Down', max_length=10)),
                ('last_refill', models.DateTimeField(default=datetime.datetime.now)),
                ('next_refill', models.DateField(default=datetime.datetime.now)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'verbose_name': 'View ATM Status',
                'verbose_name_plural': 'View ATM Status',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('Complete', 'Complete'), ('Incomplete', 'Incomplete')], default='Incomplete', max_length=10)),
                ('response_code', models.CharField(max_length=4)),
                ('transaction_type', models.CharField(choices=[('NA', 'NA'), ('Phone Change', 'Phone Change'), ('Pin Change', 'Pin Change'), ('Cash Withdrawal', 'Cash Withdrawal'), ('Cash Trasnsfer', 'Cash Trasnsfer'), ('Balance Enquiry', 'Balance Enquiry')], default='NA', max_length=15)),
                ('ATM_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Atm.ATM')),
                ('card_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Atm.Add_New_ATM_Card')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='ATM_Refill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('refill_date', models.DateField(null=True)),
                ('ATM_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Atm.ATM')),
            ],
            options={
                'verbose_name': 'ATM Refill',
                'verbose_name_plural': 'ATM Refills',
            },
        ),
    ]
