# Generated by Django 2.2.6 on 2019-11-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_New_ATM_Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=200)),
                ('pin', models.IntegerField(max_length=4)),
                ('account_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='account_extension',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
