# Generated by Django 2.2.6 on 2019-11-17 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Atm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_extension',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.CreateModel(
            name='Atm_Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=200)),
                ('date_issued', models.DateField(auto_now_add=True, null=True)),
                ('data_expire', models.DateField(null=True)),
                ('address', models.CharField(default='NA', max_length=200)),
                ('two_factor_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=10)),
                ('card_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=10)),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Atm.Account_Extension')),
            ],
        ),
    ]
