# Generated by Django 2.2.6 on 2019-11-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atm', '0002_auto_20191108_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_new_atm_card',
            name='pin',
            field=models.CharField(max_length=4),
        ),
    ]
