# Generated by Django 2.2.6 on 2019-11-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atm', '0002_auto_20191117_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atm_Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('location', models.CharField(default='NA', max_length=200)),
                ('minimum_balance', models.DecimalField(decimal_places=2, default=1000.0, max_digits=19)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('last_refill_date', models.DateField(null=True)),
                ('next_maintenance_date', models.DateField(null=True)),
            ],
        ),
    ]
