# Generated by Django 2.2.6 on 2019-11-08 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atm', '0003_auto_20191108_1909'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='add_new_atm_card',
            table='Add new ATM card',
        ),
    ]
