# Generated by Django 2.2.6 on 2019-11-17 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Atm', '0003_atm_machine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atm_Machine_Refill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('atm_branch', models.CharField(default='NA', max_length=200)),
                ('refill_date', models.DateField(auto_now_add=True, null=True)),
                ('atm_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Atm.Atm_Machine')),
            ],
        ),
    ]
