# Generated by Django 2.2.6 on 2019-11-08 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atm', '0004_auto_20191108_1915'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='add_new_atm_card',
            table='AddnewATMcard',
        ),
    ]
