# Generated by Django 2.2.6 on 2019-11-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atm', '0004_atm_machine_refill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atm_card',
            name='date_issued',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='atm_machine_refill',
            name='refill_date',
            field=models.DateField(null=True),
        ),
    ]
