# Generated by Django 2.2.6 on 2019-11-17 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Atm', '0005_auto_20191117_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Complete', 'Complete'), ('Incomplete', 'Incomplete')], default='Incomplete', max_length=10)),
                ('responce_code', models.CharField(max_length=4)),
                ('transaction_type', models.CharField(choices=[('NA', 'NA'), ('Phone Change', 'Phone Change'), ('Pin Change', 'Pin Change'), ('Cash Withdrawal', 'Cash Withdrawal'), ('Cash Trasnsfer', 'Cash Trasnsfer'), ('Balance Enquiry', 'Balance Enquiry')], default='NA', max_length=15)),
                ('atm_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Atm.Atm_Machine')),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Atm.Atm_Card')),
            ],
        ),
    ]
