# Generated by Django 2.2.6 on 2019-11-08 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atm', '0005_auto_20191108_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='add_new_atm_card',
            options={'verbose_name': 'Add new ATM card'},
        ),
        migrations.AlterModelTable(
            name='add_new_atm_card',
            table=None,
        ),
    ]
