# Generated by Django 2.2.6 on 2019-11-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atm', '0006_auto_20191108_1926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='add_new_atm_card',
            options={'verbose_name': 'New ATM card', 'verbose_name_plural': 'New ATM card'},
        ),
        migrations.AddField(
            model_name='add_new_atm_card',
            name='date_issued',
            field=models.DateField(null=True),
        ),
    ]
