# Generated by Django 2.2.6 on 2019-11-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atm', '0007_auto_20191108_2242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account_extension',
            options={'verbose_name': 'Account extension', 'verbose_name_plural': 'Account extension'},
        ),
        migrations.AddField(
            model_name='add_new_atm_card',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='add_new_atm_card',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='add_new_atm_card',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
    ]
