# Generated by Django 2.2.6 on 2019-11-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atm', '0008_auto_20191109_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_new_atm_card',
            name='id',
        ),
        migrations.AddField(
            model_name='add_new_atm_card',
            name='card_number',
            field=models.CharField(default='0', max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='add_new_atm_card',
            name='balance',
            field=models.CharField(default='0', max_length=20, null=True),
        ),
    ]
