# Generated by Django 2.2.6 on 2019-11-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atm', '0009_auto_20191109_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='View_ATM_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'View ATM Status',
                'verbose_name_plural': 'View ATM Status',
            },
        ),
    ]
