# Generated by Django 2.2.6 on 2019-11-11 22:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atm', '0010_view_atm_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='view_atm_status',
            name='ATM_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='view_atm_status',
            name='ATM_status',
            field=models.CharField(choices=[(1, 'Active'), (2, 'Down')], default=2, max_length=10),
        ),
        migrations.AddField(
            model_name='view_atm_status',
            name='last_refill',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='view_atm_status',
            name='next_refill',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
