# Generated by Django 2.2.6 on 2019-11-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atm', '0013_atm'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_new_atm_card',
            name='card_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='Inactive', max_length=10),
        ),
        migrations.AddField(
            model_name='add_new_atm_card',
            name='phone_number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='add_new_atm_card',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='add_new_atm_card',
            name='balance',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='view_atm_status',
            name='ATM_address',
            field=models.CharField(choices=[('123 Pleasant Street', '123 Pleasant Street')], max_length=200, primary_key=True, serialize=False),
        ),
    ]
