# Generated by Django 2.2.6 on 2019-11-15 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atm', '0014_auto_20191115_1801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atm',
            options={'verbose_name': 'ATM', 'verbose_name_plural': 'ATMs'},
        ),
    ]
