# Generated by Django 2.2.6 on 2019-11-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atm', '0015_auto_20191115_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view_atm_status',
            name='ATM_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DOWN', 'Down')], default='Down', max_length=10),
        ),
    ]
