# Generated by Django 2.2.6 on 2019-11-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atm', '0016_auto_20191116_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='view_atm_status',
            name='ATM',
            field=models.CharField(default=(), max_length=200),
        ),
    ]
