# Generated by Django 2.2.6 on 2019-11-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atm', '0017_view_atm_status_atm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='view_atm_status',
            name='ATM',
        ),
        migrations.AddField(
            model_name='view_atm_status',
            name='balance',
            field=models.CharField(default=(), editable=False, max_length=20),
        ),
    ]
