# Generated by Django 2.2.6 on 2019-11-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atm', '0018_auto_20191116_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view_atm_status',
            name='balance',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
