# Generated by Django 2.2.6 on 2019-11-16 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atm', '0019_auto_20191116_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='view_atm_status',
            name='balance',
        ),
    ]
