# Generated by Django 2.2.6 on 2019-11-16 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Atm', '0021_view_atm_status_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atm',
            name='balance',
        ),
    ]
