# Generated by Django 2.2.6 on 2019-11-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atm', '0023_auto_20191116_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_new_atm_card',
            name='card_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=10),
        ),
        migrations.AlterField(
            model_name='view_atm_status',
            name='ATM_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Down', 'Down')], default='Down', max_length=10),
        ),
    ]
