# Generated by Django 2.2.6 on 2019-11-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atm', '0024_auto_20191116_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account_extension',
            name='id',
        ),
        migrations.RemoveField(
            model_name='add_new_atm_card',
            name='account_number',
        ),
        migrations.AddField(
            model_name='account_extension',
            name='number',
            field=models.CharField(default='0', max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='account_extension',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
