# Generated by Django 2.2.6 on 2019-11-16 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atm', '0025_auto_20191116_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_new_atm_card',
            name='account_number',
            field=models.CharField(choices=[('0', '0')], default='0', max_length=12),
        ),
        migrations.AlterField(
            model_name='account_extension',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
