# Generated by Django 2.2.6 on 2019-11-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atm', '0026_auto_20191116_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_extension',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='add_new_atm_card',
            name='account_number',
            field=models.CharField(choices=[('111222333444', '111222333444')], default='0', max_length=12),
        ),
    ]
