# Generated by Django 2.2.6 on 2019-11-16 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Atm', '0027_auto_20191116_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_new_atm_card',
            name='account_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Atm.Account_Extension'),
        ),
    ]
