# Generated by Django 2.2.6 on 2019-11-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atm', '0030_auto_20191117_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view_atm_status',
            name='ATM_address',
            field=models.CharField(choices=[('123 Pleasant Street', '123 Pleasant Street')], max_length=200, primary_key=True, serialize=False),
        ),
    ]
